### PR TITLE
feat(Params): Simplify params services by removing select method

### PR DESCRIPTION
**Pull request by MikeRyan52**
Remove the select method from RouteParams and QueryParams. Simplify both services
by giving them an abstract token for DI and a simple projection factory. Remove
the replace method from QueryParams. Add new search method to Location to update
query params.

BREAKING CHANGE: select method removed from QueryParams and RouteParams. Use pluck instead:

  BEFORE:

  ```ts
  routeParams.select('id').subscribe(id => {});
  ```

  AFTER:

  ```ts
  routeParams.pluck('id').subscribe(id => {});
  ```

### CODE REVIEW

**Comment by brandonroberts** [comment]
Is it too early to add breaking changes to commit messages?

**Comment by MikeRyan52** [comment]
I don't think so, but also doesn't seem helpful without the change log generation. 

Should probably get that put into the build step first. Did you want to take care of that? I'll fix the commit message.

**Comment by brandonroberts** [comment]
Yea, I can work on that.

**Comment by brandonroberts** [comment]
Will you rebase?

**Comment by MikeRyan52** [comment]
Done

**Comment by brandonroberts** [comment]
Should be BREAKING CHANGE:

**Comment by MikeRyan52** [comment]
Fixed

**Pull request merged**
