### PR TITLE
add <string> for .pluck

### PR DESCRIPTION
**Pull request by Hongbo-Miao**
The can get rid of this warning in the terminal:

> Type '{}' is not assignable to type 'string'.

### CODE REVIEW

**Comment by brandonroberts** [comment]
Will you go ahead and update the other two `pluck` examples? Thanks!

**Comment by Hongbo-Miao** [comment]
@brandonroberts Sure!

**Comment by Hongbo-Miao** [comment]
@brandonroberts Done!

**Comment by brandonroberts** [comment]
Thanks!

**Comment by Hongbo-Miao** [comment]
You are welcome!

**Pull request merged**
