### PR TITLE
add Brandon's quote to readme

### PR DESCRIPTION
**Pull request by fxck**
people keep asking for difference / benefits over component router

### CODE REVIEW

**Comment by MikeRyan52** [comment]
We would like to refrain from making direct comparisons between the routers while the new component router is under development. Can you change this to simply link to the quote in the preamble instead?

**Comment by fxck** [comment]
how about this?

**Comment by brandonroberts** [comment]
I think we should table this for now. That router is deprecated and the new one isn't nearly complete yet.

**Comment by fxck** [comment]
Well I'm reposting that gitter message nearly daily in both rooms, people are asking that all the time.

**Pull request closed without merging**
